### ISSUE TITLE
Latex is not working in @doc raw for Pluto Live Docs

### ISSUE THREAD

**Issue by caxelrud** [franckgaga/ModelPredictiveControl.jl#18]
Hi,
I tried some options without success.

**Comment by caxelrud** [comment]
That is what I see now:

![image](https://github.com/franckgaga/ModelPredictiveControl.jl/assets/2330539/11936f39-4f33-45b1-bc58-3a4b1bae579d)

**Comment by franckgaga** [comment]
What version of Pluto are you using ? Did you try to open the notebook in another browser ?

**Comment by caxelrud** [comment]
This is not a problem anymore. After many updates of packages I can't tell what was causing the problem for me.

**Comment by franckgaga** [comment]
Good news, thanks!
